# Gcloud yaml

runtime: python39
entrypoint: gunicorn -b :8080 runpoint:app

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

handlers:
- url: /static
  static_dir: app/static
- url: /.*
  script: auto
  secure: always

